# Dependencies
markdown:         redcarpet
highlighter:      pygments 

# Permalinks
permalink:        pretty

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

# Setup
title:            borsuk.org
tagline:          mrb
url:              http://borsuk.org
paginate:         1
baseurl:          /
author:
  name:           Michael Borsuk (mrb)
  twitter:        wireds0ul
  email:          mrb@borsuk.org
